export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';

export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST';
export const CREATE_NOTE_FAILURE = 'CREATE_NOTE_FAILURE';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';

export const FETCH_NOTEBOOKS_REQUEST = 'FETCH_NOTEBOOKS_REQUEST';
export const FETCH_NOTEBOOKS_FAILURE = 'FETCH_NOTEBOOKS_FAILURE';
export const FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS';

export const CREATE_NOTEBOOK_REQUEST = 'CREATE_NOTEBOOK_REQUEST';
export const CREATE_NOTEBOOK_FAILURE = 'CREATE_NOTEBOOK_FAILURE';
export const CREATE_NOTEBOOK_SUCCESS = 'CREATE_NOTEBOOK_SUCCESS';

export const SAVE_POST = 'SAVE_POST';